name: HNSW CI

on: [push, pull_request]

jobs:
  test_python:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build and install
        run: python -m pip install .

      - name: Test
        timeout-minutes: 15
        run: |
          python -m unittest discover -v --start-directory examples/python --pattern "example*.py"
          python -m unittest discover -v --start-directory tests/python --pattern "bindings_test*.py"

  test_cpp:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build
        run: |
          cmake . -B build
          cmake --build build -j2
        shell: bash

      - name: Prepare test data
        run: |
          pip install numpy
          cd tests/cpp/
          python update_gen_data.py
        shell: bash

      - name: Test
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            ctest --test-dir build -C Debug -j2
          else
            ctest --test-dir build -j2
          fi
          # ctest --test-dir build
        shell: bash
